### ISSUE TITLE
Support global lix installations

### ISSUE THREAD

**Issue by Gama11** [lix-pm/lix.vscode#1]
Should actually not be too hard, would just need to find the location of the global `haxe.cmd` / `haxelib.cmd` scripts somehow.

You would also need to be able to choose between local and global in the "Initialize Project" command.

**Comment by gene-pavlovsky** [comment]
I'd like to be able to use (keep using) my global lix installation, too.

**Comment by Gama11** [comment]
`npx lix` works fine for global installations too, right?

**Comment by 0alfa** [comment]
![image](https://user-images.githubusercontent.com/39965047/166143290-04d1dfac-e5ac-4048-8a8b-98be5a39cada.png)

`npm config get prefix` should be `npm bin -g` ?

https://github.com/lix-pm/lix.vscode/blob/master/src/HaxeInstallationProvider.hx#L88
